version: 2

models: 
  - name: stg_students_info
    columns:
      - name: age_group
        data_tests:
          - accepted_values: 
              arguments:
                values: ['20-24 ans', '25-29 ans', '30-34 ans', '35-39 ans', '40-44 ans', '45-49 ans','50-54 ans', '55-59 ans', '60 ans ou plus']