version: 2

models:
  - name: int_insee_chomage_age
    description: unemployment data by age group since 2022, grouped by year
    columns:
      - name: Annee 
        description: primary key
        data_tests: 
          - not_null
          - unique
  - name: int_insee_chomage_genre
    description: unemployment data by gender group since 2022, grouped by year
    columns:
      - name: Annee 
        description: primary key
        data_tests: 
          - not_null
          - unique